VeggieTables/VeggieTables/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :profiles
  resources :farmers
  resources :restaurants
  resources :registers
  resources :members

  get 'welcome/index', :defaults => { :format => 'html'}
  root 'welcome#index', :defaults => { :format => 'html'}

end

VeggieTables/VeggieTables/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all if user.role == "admin"
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

VeggieTables/VeggieTables/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :lockable, :timeoutable
end

VeggieTables/VeggieTables/app/models/farmer.rb
class Farmer < ActiveRecord::Base

TYPE_OPTIONS = [
  'Farm',
  'Market',
  'CSA',
  'Other'
]
end

VeggieTables/VeggieTables/app/models/member.rb
class Member < ActiveRecord::Base
end

VeggieTables/VeggieTables/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :users
  TYPE_OPTIONS = [
    "Producer",
    "Restuarant",
    "Consumer"
  ]
end

VeggieTables/VeggieTables/app/models/register.rb
class Register < ActiveRecord::Base
end

VeggieTables/VeggieTables/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

VeggieTables/VeggieTables/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

  has_one :profile
end

VeggieTables/VeggieTables/app/models/welcome.rb
class Welcome < ActiveRecord::Base
  
end

VeggieTables/VeggieTables/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_default_response_format
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access Denied!"
    redirect_to root_path
  end

  def check_admin_state
    if  current_user.admin?
      yield
    else
      flash[:error] = "Permission Denied"
      redirect_to root_path
    end
  end

  def check_website_admin_state
    if current_user.website_admin?
      yield
    else
      flash[:error] = "Permission Denied"
      redirect_to root_path
    end
  end
private
  def set_default_response_format
    request_format = :json unless params[:format]
  end 

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation)} 
    devise_parameter_sanitizer.for(:account_update) << :admin
  end
    
  

end

VeggieTables/VeggieTables/app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_farmer, only: [:show, :edit, :update, :destroy]

def index
  @farmers = Farmer.all
  respond_to do |format|
    format.json { render json: @farmers.to_json}
    format.html
  end
end

def show
  respond_to do |format|
    format.json { render json: @farmer.to_json}
  end
end

def create
  @farmer = Farmer.create farmer_params
  respond_to do |format|
    format.json { render json: @farmer.to_json}
  end
  # redirect_to farmers_path
end

def new
  @farmer = Farmer.new
end

def edit
end

def destroy
end

private

def farmer_params
  params.require(:farmer).permit(
    :name,
    :location,
    :email,
    :photo,
    :description,
    :fruits,
    :vegetables,
    :herbs,
    :squash,
    :taters
    )
end

def set_farmer
  @farmer = Farmer.find params[:id]
end

end

VeggieTables/VeggieTables/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

def index
end

def new
  @profile = Profile.new
end
def create
  @register = Register.all
  @profile = Profile.create 
  respond_to do |format|  
    if @profile.save
      format.html {redirect_to new_register_path, notice: 'Created Profile'}
      format.json {render json: @profile, status: :created, location: @profile}
    else 
      format.html { render action: 'new' }
      format.json { render json: @profile.errors, status: :unprocessable_entity}
    end
  end
end
def show
end

def edit
end

def destroy
end

private

def profile_params
  params.require(:profiles).permit(
    :type,
    :address,
    :city,
    :state,
    :zipcode,
    :email,
    :name
    )
end
end

VeggieTables/VeggieTables/app/controllers/registers_controller.rb
class RegistersController < ApplicationController


end

VeggieTables/VeggieTables/app/controllers/users_controller.rb
class UsersController < ApplicationController
  ROLES = %w[admin moderator author banned]
  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :show]
end

VeggieTables/VeggieTables/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def is_admin
    respond_to do |format|
      format.json { render json: current_user.admin.to_json }
    end
  end
end 

VeggieTables/VeggieTables/app/helpers/application_helper.rb
module ApplicationHelper
end

VeggieTables/VeggieTables/app/helpers/farmers_helper.rb
module FarmersHelper
end

VeggieTables/VeggieTables/app/helpers/index_helper.rb
module IndexHelper
end

VeggieTables/VeggieTables/app/helpers/profiles_helper.rb
module ProfilesHelper
end

VeggieTables/VeggieTables/app/helpers/registers_helper.rb
module RegistersHelper
end

VeggieTables/VeggieTables/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

VeggieTables/VeggieTables/app/helpers/users_helper.rb
module UsersHelper
end

VeggieTables/VeggieTables/app/helpers/welcome_helper.rb
module WelcomeHelper
end

VeggieTables/VeggieTables/app/views/farmers/_form.html.haml
= form_for @farmer do |f|
    
  .field
    =f.label :type
    =f.select :type, options_for_select(Farmer::TYPE_OPTIONS, f.object.type), include_blank: '--select--'  .field
  .field 
    =f.label :name
    =f.text_field :name
  .field
    =f.label :location
    =f.text_area :location
  .field
    =f.label :email
    =f.text_field :email
  .field
    =f.label :photo
    =f.text_field :photo
  .field
    =f.label :description
    =f.text_area :description
  .field
    =f.label :fruits
    =f.check_box :fruits
  .field
    =f.label :vegetables
    =f.check_box :vegetables
  .field
    =f.label :herbs
    =f.check_box :herbs
  .field
    =f.label :squash
    =f.check_box :squash
  .field
    =f.label :taters
    =f.check_box :taters
  .actions
    =f.submit 'Save'

VeggieTables/VeggieTables/app/views/farmers/index.html.haml
%div{ 'ng-view':  '' }

VeggieTables/VeggieTables/app/views/farmers/new.html.haml
%h1 New farmer

= render 'form'

= link_to 'Home', root_path 

VeggieTables/VeggieTables/app/views/profiles/_form.html.haml
= form_for @profile do |f|
  .field 
    =f.label :name
    =f.text_field :name
  .field
    =f.label :type
    =f.select :type, options_for_select(Profile::TYPE_OPTIONS, f.object.type), include_blank: '--select--'
  .field
    =f.label :address
    =f.text_field :address
  .field 
    =f.label :city
    =f.text_field :city
  .field
    =f.label :state
    =f.text_field :state
  .field
    =f.label :zipcode
    =f.text_field :zipcode
  .field
    =f.label :email
    =f.text_field :email
  .action
    =f.submit 'Submit'

VeggieTables/VeggieTables/app/views/profiles/new.html.haml
= render 'form'

VeggieTables/VeggieTables/app/views/registers/new.html.haml
.jumbotron.registerMember
  %h1 LOCAL.
  %p
  %h3
    If you are interested in joining us, please see the different categories below.
    %a{:href => "#/contact"} Contact us
    with any questions or problems with your registration.
  %p
  %h3 We look forward to working with you!
 
%div{:class => "Whowillbenefit?"}
  %section.categories.col-lg-4.col-md-4.col-sm-4{"ng-controller" => "FarmController as farmCtrl"}
    %p
    %h2 growers
    %p
    %h4 Family Farmers. Backyard or community gardeners. If you have local, fresh produce to sell, we have a network of restaurants and consumers who are eager to meet you!
    %article.registerFarmer.col-lg-12.col-md-12.col-sm-12
      

    %h4 Register as a local grower:
    =link_to "Create Your LIsting",new_farmer_path
        
       
      
  %section.categories.col-lg-4.col-md-4.col-sm-4{"ng-controller" => "RestaurantController as restCtrl"}
    %p
    %h2 restaurants
    %p
    %h4
      Sometimes it can be hard to tell who is more passionate about food- the chefs who make it or the distinguished consumer.
    %p Chefs know that the first step tp making great food is getting the freshest ingredients. Join our network to contact local growers directly and get the inside scoop on what is currently available.
    %p Eating local has never been as popular as it is now. Our consumer network are almost as passionate about local food as you are! Registering with our application will allow consumers to see what you're cooking while continuing to support the local economy and environment by eating locally!

%article.registerRestaurant.col-lg-12.col-md-12.col-sm-12
  %button.newReg{"ng-click" => "new =!new", "ng-show" => "!new", :type => ""} Join Now!
  %form.col-md-5.newReg{"ng-show" => "new", "ng-submit" => "restCtrl.addRestaurant(newRestaurant)"}
    %input.col-lg-12{"ng-model" => "newRestaurant.name", :placeholder => "Name", :type => "text"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.address", :placeholder => "Street Address", :type => "text"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.city", :placeholder => "City", :type => "text"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.state", :placeholder => "State", :type => "text"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.zipcode", :placeholder => "Zip Code", :type => "text"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.website", :placeholder => "Website", :type => "url"}/
    %input.col-lg-12{"ng-model" => "newRestaurant.email", :placeholder => "e-mail", :type => "text"}/
    %button.col-lg-md-5.col-md-5.col-sm-5{:type => "submit"} Register
%section.categories.col-lg-4.col-md-4.col-sm-4
  %p
  %h2 consumers
  %p
  %h3 Definition: one who eats foods grown locally whenever possible).
  %p Great! We share your passion. We know it's important for the environment, the economy and health to support locally grown produce. By Joining Farmstand, you'll be able to network with local growers for fresh, seasonal produce. Get the inside scoop on what will be available when from your favorite growers and reserve product ahead of time for convenient pickup at your local farmer's market! (We know you shop there anyway...)
  %p Oh, and we almost forgot! We also network with restaurants who are passionate about local food as well. Check out our restaurant members.
  %article.registerConsumer.col-lg-12.col-md-12.col-sm-12
    %button.newReg{"ng-click" => "new =!new", "ng-show" => "!new", :type => ""} Join Now!
    %form.col-md-5.newReg{"ng-show" => "new", "ng-submit" => "mainCtrl.addProfile(newMember)"}
      %label{:for => "select"}
        %h4 Please select a membership category:
      %select{:id => "", :name => "", "ng-model" => "newMember.category", :required => ""}
        %option{:value => "producer"} Producer
        %option{:value => "restaurant"} Restaurant
        %option{:value => "consumer"} Consumer
      %input.col-lg-12{"ng-model" => "newMember.name", :placeholder => "Name", :type => "text"}/
      %input.col-lg-12{"ng-model" => "newMember.location", :placeholder => "Location", :type => "text"}/
      %input.col-lg-12{"ng-model" => "newMember.email", :placeholder => "email", :type => "text"}/
      %button.col-lg-md-5.col-md-5.col-sm-5{:type => "submit"} Register